# name: Get the latest Version of x-wrt Package
# on:
#  schedule:
#    - cron: '30 15 * * *'

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/6 * * * *'

# on:
#   issue_comment:
#     types: [created, edited, closed, locked, unlocked, deleted]

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

on: workflow_dispatch

env: 
  LATEST_TAG: 23.06_b202308072021

jobs:
  # get-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: test-action
  #       run: echo " action success on schedule" 

  x-wrt-sparsecheckout:
    runs-on: ubuntu-latest
    steps:
      # - name: set sparse-checkout
        # run: |
          # ls
          # echo "${{env.LATEST_TAG}}"
      - name: get the latest branch
        uses: actions/checkout@v3
        with:
           repository: x-wrt/packages
           sparse-checkout-cone-mode: false
           sparse-checkout: |
             /*
             !.circleci
             !.github
             !.keys
             !net/adguardhome
             !net/smartdns
             !net/openvpn
             !net/openvpm-easy-rsa
             !net/trojan-go
           fetch-depth: 0
           # delete paritcular tag
           # fetch all commit and tags using fetch-depth: 0
           # ref: refs/tags/${{env.LATEST_TAG}}

      - name: check to latest tag
        run: |
          # echo "before new action/checkout@3"
          # echo "workflow file: $(ls . | grep circleci)"
          # echo "adguardhome : $(ls net/ | grep adguardhome)"
          # echo "before check out: all tags:" 
          git tag | grep 23.06_b
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: check out the latest tag
        run: |
          # check out to latest tag
          # echo "LATEST_TAG now : ${{env.LATEST_TAG}}"
          git checkout tags/${{env.LATEST_TAG}}
          # echo "Makefile of abblock"
          cat net/simple-adblock/Makefile | grep "PKG_RELEASE"
      - name: prepare working directory
        run: |
          # echo "init the latest tag version by removing all .git file"
          # create a new version of packages repository
          # give token access previlege through setting action general workflow action
          rm -rf .git
          git init
          git config --global user.email ${{secrets.USEREMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          # git config --global user.email github-actions@github.com
          # git config --global user.name github-actions
          git add .
          git commit -m "latest x-wrt package : ${{env.LATEST_TAG}}" > commitlog.txt
          git branch -M main
          # add local repo as remote using to push new repo 
          REPO="https://${GITHUB_ACTOR}:${{secrets.PAT}}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          echo "${GITHUB_ACTOR}'s Working directory is '$(pwd)' GITHUB_WORKSPACE=$GITHUB_WORKSPACE BRANCH=$BRANCH"
          # echo "before merge"
          git remote add origin $REPO
          git fetch origin -a
          echo "CURRENT_TAG=$(git describe --tags `git for-each-ref --format="%(refname)" --sort=-creatordate --count=1 refs/tags`)" >> $GITHUB_ENV
      - name: push if new tag arrived
          echo "LATEST_TAG : ${{env.LATEST_TAG}}"
          echo "CURRENT_TAG: ${{env.CURRENT_TAG}}"
          if ${{env.LATEST_TAG != env.CURRENT_TAG}}
          git branch -a
          git merge --allow-unrelated-histories -s ours origin/${BRANCH}
          git checkout FETCH_HEAD -- .github/workflows/getxwrtpackages.yaml
          git commit -m "version: ${{env.LATEST_TAG}} include workflow file"
          # git tag ${{env.LATEST_TAG}}
          # cat .github/workflows/getxwrtpackages.yaml
          # git push -u origin --tags
          # push both branch and tags
          git push --atomic origin ${BRANCH} ${{env.LATEST_TAG}}
